### PR TITLE
Update Fedora instructions

### PR DESCRIPTION
**Pull request by igor-raits**

### CODE REVIEW

**Comment by igor-raits** [comment]
@jmmv also would be nice if you could do `fedpkg retire` for `kyua-cli` and `kyua-testers`.

**Comment by jmmv** [comment]
W00t! Somebody (you?) packaged repackaged Kyua as a new RPM? Thanks! I opened a bug a long time ago with a preliminary spec but never got a responsive reviewer for it :-(

**Comment by igor-raits** [comment]
@jmmv I will add you as admins ;) and don't hesitate to improve it ;)

**Comment by igor-raits** [comment]
Done. https://src.fedoraproject.org/rpms/kyua

**Comment by jmmv** [comment]
@googlebot rescan

(Mass-triggering a rescan of all open PRs as I have just configured automated CLA checks but the bot won't go through the backlog on its own.)

**Comment by igor-raits** [comment]
@jmmv why do you need CLA? :/

**Comment by ngie-eign** [comment]
> @jmmv why do you need CLA? :/

This is a Google sponsored project, so one needs to sign the Google CLA in order to contribute to it.

**Pull request merged**
