### PR TITLE
Fix regex that breaks integration/cmd_report_test:verbose

### PR DESCRIPTION
**Pull request by vangyzen**

### CODE REVIEW

**Comment by vangyzen** [comment]
@googlebot I signed it!

**Review by ngie-eign — APPROVED** [review]
LGTM at least, but I don't have merge powers.

**Comment by asomers** [comment]
@vangyzen  would you mind resubmitting this PR to https://github.com/freebsd/kyua , now that we've forked the project?

**Comment by vangyzen** [comment]
@asomers  Done:  https://github.com/freebsd/kyua/pull/7

**Pull request merged**
