### PR TITLE
Add Cirrus CI config for FreeBSD build

### PR DESCRIPTION
**Pull request by lwhsu**
This is not covering all the things in Travis-CI, but should be a good start for testing on BSD systems.

### CODE REVIEW

**Comment by asomers** [comment]
Do you realize that every task spins up a new VM?  This would run faster if you condense everything into one task (with the two-release matrix) and used multiple scripts instead.

**Comment by lwhsu** [comment]
Yes, my first approach was trying to align with what we did with travis-ci. I was also thinking of integrating everything into one task, but that has one drawback: we cannot easily tell the failure is in build or just api-doc, and it would get worse if we add gcc build later. BTW, the tasks are executed in parallel, perhaps not slower than executing the checks sequentially. It does consumes more VM resources, though.

**Comment by jmmv** [comment]
@googlebot rescan

(Mass-triggering a rescan of all open PRs as I have just configured automated CLA checks but the bot won't go through the backlog on its own.)

**Comment by ngie-eign** [comment]
@lwhsu: I think it makes more sense to just run dist_check on FreeBSD.

Sidenote: some of the kyua tests are crashing on Jenkins, btw. Do they occur on the cirrus runs?

**Comment by asomers** [comment]
@lwhsu would you mind resubmitting this PR to https://github.com/freebsd/kyua , now that we've forked the project?

**Comment by lwhsu** [comment]
https://github.com/freebsd/kyua/pull/1

This has merged with https://github.com/jmmv/kyua/pull/208

**Pull request closed without merging**
