### PR TITLE
 Adding TravisCI into README.md

### PR DESCRIPTION
**Pull request by concatime**

### CODE REVIEW

**Comment by concatime** [comment]
[`Line too long to fit on screen`](//travis-ci.org/jmmv/kyua/jobs/307381435#L1093). Seriously!? C’mon…

**Comment by jmmv** [comment]
@googlebot rescan

(Mass-triggering a rescan of all open PRs as I have just configured automated CLA checks but the bot won't go through the backlog on its own.)

**Comment by concatime** [comment]
I will not sign the CLA because it requires a Google account. Do WTF you want with my PR.
Thank you.

**Comment by jmmv** [comment]
Thank you for your interest. I will disregard this PR then.

I'll just say that this kind of behavior (the tone in your last response) is not welcome in the open-source community and I will not accept it in my projects.

**Pull request closed without merging**
